In [1]:
import pandas as pd

df = pd.read_csv('bemo_prompts_dataset.csv')

In [2]:
df.sample(5)

,prompt,general,smart_home,todo,mail
229,"Start the vacuum cleaner, add 'finish the proj...",0,1,1,1
163,Remember to call mom tomorrow and send an upda...,0,0,1,1
12,How do I improve my productivity?,1,0,0,0
171,"How's the weather today, dim the bedroom light...",1,1,1,0
237,"Open the curtains in the living room, add a ta...",0,1,1,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   prompt      250 non-null    object
 1   general     250 non-null    int64
 2   smart_home  250 non-null    int64
 3   todo        250 non-null    int64
 4   mail        250 non-null    int64
dtypes: int64(4), object(1)
memory usage: 9.9+ KB

In [4]:
# Shuffle the data
df = df.sample(frac=1).reset_index(drop=True)

In [5]:
prompts = df['prompt'].values.tolist()
prompts[:5]

['Activate the home surveillance system and schedule a conference call for Monday.',
 'Lock the front door.',
 'Close the window blinds.',
 "What's the best movie tonight, open the curtains in the living room, and email the summary of the meeting.",
 'Can you tell me a fun fact, lock the front door, remind me to submit the report, and forward the latest report via email.']

In [6]:
labels = df.drop(columns=["prompt"]).values.tolist()
labels[:5]

[[0, 1, 1, 0], [0, 1, 0, 0], [0, 1, 0, 0], [1, 1, 0, 1], [1, 1, 1, 1]]

In [7]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

device = "cuda"
tokenizer = AutoTokenizer.from_pretrained("humarin/chatgpt_paraphraser_on_T5_base")
model = AutoModelForSeq2SeqLM.from_pretrained("humarin/chatgpt_paraphraser_on_T5_base").to(device)

In [8]:
def paraphrase(
    question,
    num_beams=5,
    num_beam_groups=5,
    num_return_sequences=5,
    repetition_penalty=1.5,
    diversity_penalty=0.5,
    no_repeat_ngram_size=2,
    temperature=0.7,
    max_length=128
):
    input_ids = tokenizer(
        f'paraphrase: {question}',
        return_tensors="pt", padding="longest",
        max_length=max_length,
        truncation=True,
    ).input_ids.to(device)
    
    outputs = model.generate(
        input_ids, temperature=temperature, repetition_penalty=repetition_penalty,
        num_return_sequences=num_return_sequences, no_repeat_ngram_size=no_repeat_ngram_size,
        num_beams=num_beams, num_beam_groups=num_beam_groups,
        max_length=max_length, diversity_penalty=diversity_penalty
    )

    result = tokenizer.batch_decode(outputs, skip_special_tokens=True)

    return result

In [9]:
paraphrase("What is the capital of France?")

/home/momad/projects/BEMO/.venv/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

['What city serves as the capital of France?',
 'What is the name of the capital city in France?',
 'In which city is the capital of France located?',
 'Which city is designated as the capital of France?',
 'What is the name of the city that serves as the capital of France?']

In [10]:
paraphrased_prompts = []
paraphrased_labels = []

for i, prompt in enumerate(prompts):
    print(f"Processing prompt {i+1}/{len(prompts)}")
    results = paraphrase(prompt)
    paraphrased_prompts.extend(results)
    for _ in range(len(results)):
        paraphrased_labels.append(labels[i])

Processing prompt 1/250
Processing prompt 2/250
Processing prompt 3/250
Processing prompt 4/250
Processing prompt 5/250
Processing prompt 6/250
Processing prompt 7/250
Processing prompt 8/250
Processing prompt 9/250
Processing prompt 10/250
Processing prompt 11/250
Processing prompt 12/250
Processing prompt 13/250
Processing prompt 14/250
Processing prompt 15/250
Processing prompt 16/250
Processing prompt 17/250
Processing prompt 18/250
Processing prompt 19/250
Processing prompt 20/250
Processing prompt 21/250
Processing prompt 22/250
Processing prompt 23/250
Processing prompt 24/250
Processing prompt 25/250
Processing prompt 26/250
Processing prompt 27/250
Processing prompt 28/250
Processing prompt 29/250
Processing prompt 30/250
Processing prompt 31/250
Processing prompt 32/250
Processing prompt 33/250
Processing prompt 34/250
Processing prompt 35/250
Processing prompt 36/250
Processing prompt 37/250
Processing prompt 38/250
Processing prompt 39/250
Processing prompt 40/250
Processing prompt 41/250
Processing prompt 42/250
Processing prompt 43/250
Processing prompt 44/250
Processing prompt 45/250
Processing prompt 46/250
Processing prompt 47/250
Processing prompt 48/250
Processing prompt 49/250
Processing prompt 50/250
Processing prompt 51/250
Processing prompt 52/250
Processing prompt 53/250
Processing prompt 54/250
Processing prompt 55/250
Processing prompt 56/250
Processing prompt 57/250
Processing prompt 58/250
Processing prompt 59/250
Processing prompt 60/250
Processing prompt 61/250
Processing prompt 62/250
Processing prompt 63/250
Processing prompt 64/250
Processing prompt 65/250
Processing prompt 66/250
Processing prompt 67/250
Processing prompt 68/250
Processing prompt 69/250
Processing prompt 70/250
Processing prompt 71/250
Processing prompt 72/250
Processing prompt 73/250
Processing prompt 74/250
Processing prompt 75/250
Processing prompt 76/250
Processing prompt 77/250
Processing prompt 78/250
Processing prompt 79/250
Processing prompt 80/250
Processing prompt 81/250
Processing prompt 82/250
Processing prompt 83/250
Processing prompt 84/250
Processing prompt 85/250
Processing prompt 86/250
Processing prompt 87/250
Processing prompt 88/250
Processing prompt 89/250
Processing prompt 90/250
Processing prompt 91/250
Processing prompt 92/250
Processing prompt 93/250
Processing prompt 94/250
Processing prompt 95/250
Processing prompt 96/250
Processing prompt 97/250
Processing prompt 98/250
Processing prompt 99/250
Processing prompt 100/250
Processing prompt 101/250
Processing prompt 102/250
Processing prompt 103/250
Processing prompt 104/250
Processing prompt 105/250
Processing prompt 106/250
Processing prompt 107/250
Processing prompt 108/250
Processing prompt 109/250
Processing prompt 110/250
Processing prompt 111/250
Processing prompt 112/250
Processing prompt 113/250
Processing prompt 114/250
Processing prompt 115/250
Processing prompt 116/250
Processing prompt 117/250
Processing prompt 118/250
Processing prompt 119/250
Processing prompt 120/250
Processing prompt 121/250
Processing prompt 122/250
Processing prompt 123/250
Processing prompt 124/250
Processing prompt 125/250
Processing prompt 126/250
Processing prompt 127/250
Processing prompt 128/250
Processing prompt 129/250
Processing prompt 130/250
Processing prompt 131/250
Processing prompt 132/250
Processing prompt 133/250
Processing prompt 134/250
Processing prompt 135/250
Processing prompt 136/250
Processing prompt 137/250
Processing prompt 138/250
Processing prompt 139/250
Processing prompt 140/250
Processing prompt 141/250
Processing prompt 142/250
Processing prompt 143/250
Processing prompt 144/250
Processing prompt 145/250
Processing prompt 146/250
Processing prompt 147/250
Processing prompt 148/250
Processing prompt 149/250
Processing prompt 150/250
Processing prompt 151/250
Processing prompt 152/250
Processing prompt 153/250
Processing prompt 154/250
Processing prompt 155/250
Processing prompt 156/250
Processing prompt 157/250
Processing prompt 158/250
Processing prompt 159/250
Processing prompt 160/250
Processing prompt 161/250
Processing prompt 162/250
Processing prompt 163/250
Processing prompt 164/250
Processing prompt 165/250
Processing prompt 166/250
Processing prompt 167/250
Processing prompt 168/250
Processing prompt 169/250
Processing prompt 170/250
Processing prompt 171/250
Processing prompt 172/250
Processing prompt 173/250
Processing prompt 174/250
Processing prompt 175/250
Processing prompt 176/250
Processing prompt 177/250
Processing prompt 178/250
Processing prompt 179/250
Processing prompt 180/250
Processing prompt 181/250
Processing prompt 182/250
Processing prompt 183/250
Processing prompt 184/250
Processing prompt 185/250
Processing prompt 186/250
Processing prompt 187/250
Processing prompt 188/250
Processing prompt 189/250
Processing prompt 190/250
Processing prompt 191/250
Processing prompt 192/250
Processing prompt 193/250
Processing prompt 194/250
Processing prompt 195/250
Processing prompt 196/250
Processing prompt 197/250
Processing prompt 198/250
Processing prompt 199/250
Processing prompt 200/250
Processing prompt 201/250
Processing prompt 202/250
Processing prompt 203/250
Processing prompt 204/250
Processing prompt 205/250
Processing prompt 206/250
Processing prompt 207/250
Processing prompt 208/250
Processing prompt 209/250
Processing prompt 210/250
Processing prompt 211/250
Processing prompt 212/250
Processing prompt 213/250
Processing prompt 214/250
Processing prompt 215/250
Processing prompt 216/250
Processing prompt 217/250
Processing prompt 218/250
Processing prompt 219/250
Processing prompt 220/250
Processing prompt 221/250
Processing prompt 222/250
Processing prompt 223/250
Processing prompt 224/250
Processing prompt 225/250
Processing prompt 226/250
Processing prompt 227/250
Processing prompt 228/250
Processing prompt 229/250
Processing prompt 230/250
Processing prompt 231/250
Processing prompt 232/250
Processing prompt 233/250
Processing prompt 234/250
Processing prompt 235/250
Processing prompt 236/250
Processing prompt 237/250
Processing prompt 238/250
Processing prompt 239/250
Processing prompt 240/250
Processing prompt 241/250
Processing prompt 242/250
Processing prompt 243/250
Processing prompt 244/250
Processing prompt 245/250
Processing prompt 246/250
Processing prompt 247/250
Processing prompt 248/250
Processing prompt 249/250
Processing prompt 250/250

In [11]:
print(len(paraphrased_prompts), len(paraphrased_labels))

1250 1250

In [12]:
paraphrased_prompts[10:15]

['Close the window blinds.',
 'Close the window blinds.',
 'Open the window curtains.',
 'Close the window blinds.',
 'Remove the window curtains.']

In [13]:
paraphrased_labels[10:15]

[[0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0]]

In [14]:
para_df = pd.DataFrame({
    "prompt": paraphrased_prompts,
    "general": [l[0] for l in paraphrased_labels],
    "smart_home": [l[1] for l in paraphrased_labels],
    "todo": [l[2] for l in paraphrased_labels],
    "mail": [l[3] for l in paraphrased_labels],
})

In [15]:
para_df.sample(5)

,prompt,general,smart_home,todo,mail
222,"What is the definition of quantum physics, wha...",1,1,1,0
1108,Send an email to invite .,0,0,0,1
379,"Adjust the dining room lighting, schedule a cl...",0,1,1,1
1057,How does meditation and relaxing music contrib...,1,1,0,0
948,"Tell me what's the latest update, set the ther...",1,1,0,1

In [16]:
import os
from dotenv import load_dotenv, find_dotenv, dotenv_values

load_dotenv()
os.environ["HUGGINGFACEHUB_API_TOKEN"] = dotenv_values(find_dotenv())[
    "HUGGINGFACE_API_KEY_TEST"
]
gemini_api_key = dotenv_values(find_dotenv())["GEMINI_API_KEY_TEST"]
os.environ["GOOGLE_API_KEY"] = gemini_api_key

In [17]:
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=2,
)

In [ ]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser